<?php
declare(strict_types=1);

use Phinx\Migration\AbstractMigration;
use Phinx\Db\Adapter\MysqlAdapter;

final class ChangesSellerTable extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * https://book.cakephp.org/phinx/0/en/migrations.html#the-change-method
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change(): void
    {
        $this->table('pct_order_borrower_selller_agent_info')->drop()->save();
        $this->table('pct_order_borrower_selller_hoa_info')->drop()->save();
        $this->table('pct_order_borrower_selller_info')->drop()->save();
        $this->table('pct_order_borrower_selller_mortgage_info')->drop()->save();
        $this->table('pct_order_borrower_selller_other_info')->drop()->save();
        $this->table('pct_order_borrower_selller_property_info')->drop()->save();

        $table = $this->table('pct_order_borrower_seller_owner_escrow_info');
        $table->addColumn('order_id', 'integer')
            ->addColumn('seller_name', 'string', ['null' => true])
			->addColumn('escrow_home_phone_number', 'string', ['null' => true])
			->addColumn('work_phone_number', 'string', ['null' => true])
            ->addColumn('fax_number', 'string', ['null' => true])
			->addColumn('cell_phone_number', 'string', ['null' => true])
            ->addColumn('email_address', 'string', ['null' => true])
			->addColumn('cell_phone_number_2', 'string', ['null' => true])
            ->addColumn('escrow_ssn', 'string', ['null' => true])
			->addColumn('ssn_2', 'string', ['null' => true])
            ->addColumn('property_address', 'string', ['null' => true])
			->addColumn('seller_current_mailing_address', 'string', ['null' => true ])
            ->addColumn('seller_mailing_address_after_close_escrow', 'string', ['null' => true ])
			->addColumn('seller_mailing_address_after_close_escrow_2', 'string', ['null' => true ])
            ->addColumn('first_trust_deed_lender', 'string', ['null' => true])
			->addColumn('lender_address', 'string', ['null' => true])
            ->addColumn('loan_number', 'string', ['null' => true])
			->addColumn('lender_phone_number', 'string', ['null' => true])
            ->addColumn('unpaid_principal_balance', 'string', ['null' => true])
			->addColumn('next_due', 'string', ['null' => true])
            ->addColumn('type_of_loan', 'string', ['null' => true])
			->addColumn('va', 'string', ['null' => true])
            ->addColumn('fha', 'string', ['null' => true])
			->addColumn('conventional', 'string', ['null' => true])
            ->addColumn('taxes', 'string', ['null' => true])
			->addColumn('paid', 'string', ['null' => true])
            ->addColumn('unpaid', 'string', ['null' => true])
			->addColumn('is_impound_acc', 'string', ['null' => true])
            ->addColumn('second_trust_deed_lender', 'string', ['null' => true])
			->addColumn('second_lender_address', 'string', ['null' => true])
            ->addColumn('second_loan_number', 'string', ['null' => true])
            ->addColumn('second_lender_phone_number', 'string', ['null' => true])
			->addColumn('second_unpaid_principal_balance', 'string', ['null' => true])
            ->addColumn('second_type_of_loan', 'string', ['null' => true])
			->addColumn('second_va', 'string', ['null' => true])
            ->addColumn('second_fha', 'string', ['null' => true])
			->addColumn('second_conventional', 'string', ['null' => true])
            ->addColumn('homeowner_association', 'string', ['null' => true])
			->addColumn('management_company', 'string', ['null' => true])
            ->addColumn('management_mailing_address', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
			->addColumn('contact_person', 'string', ['null' => true])
            ->addColumn('management_phone_number', 'string', ['null' => true])
            ->addColumn('second_homeowner_association', 'string', ['null' => true])
			->addColumn('second_management_company', 'string', ['null' => true])
            ->addColumn('second_management_mailing_address', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
			->addColumn('second_contact_person', 'string', ['null' => true])
            ->addColumn('second_management_phone_number', 'string', ['null' => true])
			->addColumn('water_company_name', 'string', ['null' => true])
            ->addColumn('water_contract_name', 'string', ['null' => true])
			->addColumn('water_company_address', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
            ->addColumn('water_company_phone', 'string', ['null' => true])
			->addColumn('amount_of_assessment', 'string', ['null' => true])
            ->addColumn('water_next_due', 'string', ['null' => true])
            ->addColumn('no_of_shares', 'string', ['null' => true])
			->addColumn('date', 'string', ['null' => true])
            ->addColumn('escrow_signature', 'string', ['null' => true])
			->addTimestamps()
            ->create();

            $table = $this->table('pct_order_borrower_seller_statement_of_info');
            $table->addColumn('order_id', 'integer')
                ->addColumn('first_name', 'string', ['null' => true])
                ->addColumn('middle_name', 'string', ['null' => true])
                ->addColumn('last_name', 'string', ['null' => true])
                ->addColumn('maiden_name', 'string', ['null' => true])
                ->addColumn('date_of_birth', 'string', ['null' => true])
                ->addColumn('home_phone_number', 'string', ['null' => true])
                ->addColumn('business_phone_number', 'string', ['null' => true])
                ->addColumn('birthplace', 'string', ['null' => true])
                ->addColumn('ssn', 'string', ['null' => true])
                ->addColumn('driver_license_no', 'string', ['null' => true])
                ->addColumn('another_name_that_used', 'string', ['null' => true])
                ->addColumn('residence_state', 'string', ['null' => true])
                ->addColumn('lived_year', 'string', ['null' => true])
                ->addColumn('is_married', 'string', ['null' => true])
                ->addColumn('date_and_place_marriage', 'string', ['null' => true])
                ->addColumn('spouse_first_name', 'string', ['null' => true])
                ->addColumn('spouse_middle_name', 'string', ['null' => true])
                ->addColumn('spouse_last_name', 'string', ['null' => true])
                ->addColumn('spouse_maiden_name', 'string', ['null' => true])
                ->addColumn('spouse_date_of_birth', 'string', ['null' => true])
                ->addColumn('spouse_home_phone_number', 'string', ['null' => true])
                ->addColumn('spouse_business_phone_number', 'string', ['null' => true])
                ->addColumn('spouse_birthplace', 'string', ['null' => true])
                ->addColumn('spouse_ssn', 'string', ['null' => true])
                ->addColumn('spouse_driver_license_no', 'string', ['null' => true])
                ->addColumn('spouse_another_name_that_used', 'string', ['null' => true])
                ->addColumn('spouse_state_residence', 'string', ['null' => true])
                ->addColumn('spouse_lived_year', 'string', ['null' => true])
                ->addColumn('is_domestic_partner', 'string', ['null' => true]) 
                ->addColumn('domestic_first_name', 'string', ['null' => true])
                ->addColumn('domestic_middle_name', 'string', ['null' => true])
                ->addColumn('domestic_last_name', 'string', ['null' => true])
                ->addColumn('domestic_maiden_name', 'string', ['null' => true])
                ->addColumn('domestic_date_of_birth', 'string', ['null' => true])
                ->addColumn('domestic_home_phone_number', 'string', ['null' => true])
                ->addColumn('domestic_business_phone_number', 'string', ['null' => true])
                ->addColumn('domestic_birthplace', 'string', ['null' => true])
                ->addColumn('domestic_ssn', 'string', ['null' => true])
                ->addColumn('domestic_driver_license_no', 'string', ['null' => true])
                ->addColumn('domestic_another_name_that_used', 'string', ['null' => true])
                ->addColumn('domestic_state_residence', 'string', ['null' => true])
                ->addColumn('domestic_lived_year', 'string', ['null' => true])
                ->addColumn('residence_number_street', 'string', ['null' => true])
                ->addColumn('residence_city', 'string', ['null' => true])
                ->addColumn('residence_from_date_to_date', 'string', ['null' => true])
                ->addColumn('second_residence_number_street', 'string', ['null' => true])
                ->addColumn('second_residence_city', 'string', ['null' => true])
                ->addColumn('second_residence_from_date_to_date', 'string', ['null' => true])
                ->addColumn('firm_or_business_name', 'string', ['null' => true])
                ->addColumn('business_address', 'string', ['null' => true])
                ->addColumn('business_from_date_to_date', 'string', ['null' => true])
                ->addColumn('second_firm_or_business_name', 'string', ['null' => true])
                ->addColumn('second_business_address', 'string', ['null' => true])
                ->addColumn('second_business_from_date_to_date', 'string', ['null' => true])
                ->addColumn('is_buyer_intends', 'string', ['null' => true])
                ->addColumn('owner_street_address', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
                ->addColumn('unimproved', 'string', ['null' => true])
                ->addColumn('single_family', 'string', ['null' => true])
                ->addColumn('condo_unit', 'string', ['null' => true])
                ->addColumn('other', 'string', ['null' => true])
                ->addColumn('is_improvement', 'string', ['null' => true])
                ->addColumn('is_materials', 'string', ['null' => true])
                ->addColumn('is_loan', 'string', ['null' => true])
                ->addColumn('lender', 'string', ['null' => true])
                ->addColumn('loan_amount', 'string', ['null' => true])
                ->addColumn('loan_account', 'string', ['null' => true])
                ->addColumn('second_lender', 'string', ['null' => true])
                ->addColumn('second_loan_amount', 'string', ['null' => true])
                ->addColumn('second_loan_account', 'string', ['null' => true])
                ->addColumn('executed_date', 'string', ['null' => true])
                ->addColumn('executed_year', 'string', ['null' => true])
                ->addColumn('executed_time', 'string', ['null' => true])
                ->addColumn('signature', 'string', ['null' => true])
                ->addColumn('second_signature', 'string', ['null' => true])
                ->addTimestamps()
                ->create();

            $table = $this->table('pct_order_borrower_seller_593_c_form_part_1');
            $table->addColumn('order_id', 'integer')
                ->addColumn('is_amended', 'string', ['null' => true])
                ->addColumn('remitter_info', 'string', ['null' => true])
                ->addColumn('business_name', 'string', ['null' => true])
                ->addColumn('business_num', 'string', ['null' => true])
                ->addColumn('remitter_first_name', 'string', ['null' => true])
                ->addColumn('remitter_initial_name', 'string', ['null' => true])
                ->addColumn('remitter_last_name', 'string', ['null' => true])
                ->addColumn('remitter_ssn_or_itin', 'string', ['null' => true])
                ->addColumn('remitter_address', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
                ->addColumn('remitter_city', 'string', ['null' => true])
                ->addColumn('remitter_state', 'string', ['null' => true])
                ->addColumn('remitter_zip_code', 'string', ['null' => true])
                ->addColumn('remitter_telephone_num', 'string', ['null' => true])
                ->addColumn('trust_types', 'string', ['null' => true])
                ->addColumn('transferor_first_name', 'string', ['null' => true])
                ->addColumn('transferor_initial_name', 'string', ['null' => true])
                ->addColumn('transferor_last_name', 'string', ['null' => true])
                ->addColumn('transferor_ssn_or_itin', 'string', ['null' => true])
                ->addColumn('transferor_spouse_first_name', 'string', ['null' => true])
                ->addColumn('transferor_spouse_middle_name', 'string', ['null' => true])
                ->addColumn('transferor_spouse_last_name', 'string', ['null' => true])
                ->addColumn('transferor_spouse_ssn_or_itin', 'string', ['null' => true])
                ->addColumn('nongrantor_trust_name', 'string', ['null' => true])
                ->addColumn('transferor_business_num', 'string', ['null' => true])
                ->addColumn('transferor_address', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
                ->addColumn('transferor_city', 'string', ['null' => true])
                ->addColumn('transferor_state', 'string', ['null' => true])
                ->addColumn('transferor_zip_code', 'string', ['null' => true]) 
                ->addColumn('transferor_telephone_number', 'string', ['null' => true])
                ->addColumn('transferor_property_address', 'text', ['null' => true, 'limit' => MysqlAdapter::TEXT_LONG])
                ->addColumn('ownership_percentage', 'string', ['null' => true])
                ->addColumn('certifications', 'string', ['null' => true])
                ->addColumn('remitter_name', 'string', ['null' => true])
                ->addColumn('remitter_ssn_fein', 'string', ['null' => true])
                ->addColumn('transferee_first_name', 'string', ['null' => true])
                ->addColumn('transferee_initial_name', 'string', ['null' => true])
                ->addColumn('transferee_last_name', 'string', ['null' => true])
                ->addColumn('transferee_ssn_or_itin', 'string', ['null' => true])
                ->addColumn('transferee_spouse_first_name', 'string', ['null' => true])
                ->addColumn('transferee_spouse_initial_name', 'string', ['null' => true])
                ->addColumn('transferee_spouse_last_name', 'string', ['null' => true])
                ->addTimestamps()
                ->create();

            $table = $this->table('pct_order_borrower_seller_593_c_form_part_2');
            $table->addColumn('order_id', 'integer')    
                ->addColumn('transferee_spouse_ssn_or_itin', 'string', ['null' => true])
                ->addColumn('transferee_nongrantor_trust_name', 'string', ['null' => true])
                ->addColumn('transferee_business_num', 'string', ['null' => true])
                ->addColumn('transferee_address', 'string', ['null' => true])
                ->addColumn('transferee_city', 'string', ['null' => true])
                ->addColumn('transferee_state', 'string', ['null' => true])
                ->addColumn('transferee_zip_code', 'string', ['null' => true])
                ->addColumn('transferee_telephone_number', 'string', ['null' => true])
                ->addColumn('principal_amount_of_promissory_note', 'string', ['null' => true])
                ->addColumn('installment_amount', 'string', ['null' => true])
                ->addColumn('principal_interrest_rate', 'string', ['null' => true])
                ->addColumn('repayment_period', 'string', ['null' => true])
                ->addColumn('selling_price', 'string', ['null' => true])
                ->addColumn('selling_expenses', 'string', ['null' => true])
                ->addColumn('amount_realized', 'string', ['null' => true])
                ->addColumn('paid_price_to_purchase', 'string', ['null' => true])
                ->addColumn('seller_paid_months', 'string', ['null' => true])
                ->addColumn('seller_depreciation', 'string', ['null' => true])
                ->addColumn('other_decreases', 'string', ['null' => true])
                ->addColumn('total_decrease_line_17', 'string', ['null' => true])
                ->addColumn('subtract_line_20', 'string', ['null' => true])
                ->addColumn('cost_of_addition', 'string', ['null' => true])
                ->addColumn('other_increase_to_basis', 'string', ['null' => true])
                ->addColumn('total_decrease_line_22', 'string', ['null' => true])
                ->addColumn('adjusted_basis_line_21', 'string', ['null' => true])
                ->addColumn('suspended_passive_lossed', 'string', ['null' => true])
                ->addColumn('add_line_25', 'string', ['null' => true])
                ->addColumn('estimated_gain_or_loss', 'string', ['null' => true])
                ->addColumn('remitter_name_2', 'string', ['null' => true])
                ->addColumn('remitter_ssn_itin_fein_2', 'string', ['null' => true])
                ->addColumn('calculation_amount', 'string', ['null' => true])
                ->addColumn('calculation_amount_value', 'string', ['null' => true])
                ->addColumn('sales_price_withholding_amount', 'string', ['null' => true])
                ->addColumn('escrow_exchange_number', 'string', ['null' => true])
                ->addColumn('date_of_transfer', 'string', ['null' => true])
                ->addColumn('boot_amount', 'string', ['null' => true])
                ->addColumn('exchange_ownership_percentage_from', 'string', ['null' => true])
                ->addColumn('exchange_ownership_percentage_to', 'string', ['null' => true])
                ->addColumn('amount_withheld_from', 'string', ['null' => true])
                ->addColumn('amount_withheld_to', 'string', ['null' => true])
                ->addColumn('transaction', 'string', ['null' => true])
                ->addColumn('with_holding', 'string', ['null' => true])
                ->addColumn('amount_withheld', 'string', ['null' => true])
                ->addColumn('perjury', 'string', ['null' => true])
                ->addColumn('seller_transferor_signature', 'string', ['null' => true])
                ->addColumn('seller_transferor_date', 'string', ['null' => true])
                ->addColumn('seller_transferor_spouse_signature', 'string', ['null' => true])
                ->addColumn('seller_transferor_spouse_date', 'string', ['null' => true])
                ->addColumn('buyer_transferor_signature', 'string', ['null' => true])
                ->addColumn('buyer_transferor_date', 'string', ['null' => true])
                ->addColumn('buyer_transferor_spouse_signature', 'string', ['null' => true])
                ->addColumn('buyer_transferor_spouse_date', 'string', ['null' => true])
                ->addTimestamps()
                ->create();

            $table = $this->table('pct_order_borrower_seller_other_info');
            $table->addColumn('order_id', 'integer')
                ->addColumn('date_of_closing', 'string', ['null' => true])
                ->addColumn('sellers_name', 'string', ['null' => true])
                ->addColumn('personal_representative', 'string', ['null' => true])
                ->addColumn('federal_tax', 'string', ['null' => true])
                ->addColumn('total_consideration', 'string', ['null' => true])
                ->addColumn('percentage_of_ownership', 'string', ['null' => true])
                ->addColumn('gross_allocated', 'string', ['null' => true])
                ->addColumn('is_exchange', 'string', ['null' => true])
                ->addColumn('tax_credit', 'string', ['null' => true])
                ->addColumn('mailing_address_1099_s_1', 'string', ['null' => true])
                ->addColumn('mailing_address_1099_s_2', 'string', ['null' => true])
                ->addColumn('is_outside', 'string', ['null' => true])
                ->addColumn('is_regulations', 'string', ['null' => true])
                ->addColumn('tranferor_signature', 'string', ['null' => true])
                ->addColumn('spouse_signature', 'string', ['null' => true])
                ->addColumn('spouse_date', 'string', ['null' => true])
                ->addColumn('taxpayer_identifying_num', 'string', ['null' => true])
                ->addColumn('home_address', 'string', ['null' => true])
                ->addColumn('home_address_2', 'string', ['null' => true])
                ->addColumn('firpta_date', 'string', ['null' => true])
                ->addColumn('firpta_signature', 'string', ['null' => true])
                ->addColumn('tenant_id', 'string', ['null' => true])
                ->addColumn('doc_type', 'string', ['null' => true])
                ->addTimestamps()
                ->create();

    }
}
